apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-innsyn-api
  namespace: default
  labels:
    team: digisos
spec:
  image: navikt/sosialhjelp-innsyn-api:latest
  port: 8080
  liveness:
    path: /internal/isAlive
  readiness:
    path: /internal/isReady
  prometheus:
    path: /metrics
  replicas:
    min: 1
    max: 4
  vault:
    enabled: false
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi