apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: digisos
  name: sosialhjelp-innsyn-api-redis
  namespace: default
spec:
  image: redis:5-alpine # or a custom Redis-image
  port: 6379
  replicas: # A single Redis-app doesn't scale
    min: 1
    max: 1
  resources: # you need to monitor need your self
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 256Mi
  service:
    port: 6379