spring:
  main:
    banner-mode: 'off'
  application:
    name: "sosialhjelp-innsyn-api"
  redis:
    host: ${REDIS_HOST}
    port: 6379
    password: ${REDIS_PASSWORD}
  session:
    store-type: redis

server:
  servlet:
    context-path: '/sosialhjelp/innsyn-api'
    session:
      cookie:
        name: sosialhjelp-innsyn-id
        path: /sosialhjelp
        secure: true
        max-age: 30M
        http-only: true
  max-http-header-size: 16KB
  shutdown: graceful


# Prometheus
management:
  endpoints:
    web:
      base-path: "/internal"
      exposure:
        include: info, health, metrics, prometheus

springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED}
  swagger-ui:
    path: swagger-ui.html
  pathsToMatch: /**/api/v1/**

#Environment-variabler som settes av NAIS
client:
  fiks_digisos_endpoint_url: ${FIKS_DIGISOS_ENDPOINT_URL}
  fiks_dokumentlager_endpoint_url: ${FIKS_DOKUMENTLAGER_ENDPOINT_URL}
  fiks_svar_ut_endpoint_url: ${FIKS_SVAR_UT_ENDPOINT_URL}
  fiks_integrasjonid: ${INTEGRASJONSID_FIKS}
  fiks_integrasjonid_kommune: ${INTEGRASJONSID_FIKS_KOMMUNE}
  fiks_integrasjonpassord: ${INTEGRASJONPASSORD_FIKS}
  fiks_integrasjonpassord_kommune: ${INTEGRASJONPASSORD_FIKS_KOMMUNE}
  norg_url: ${NORG_URL}
  pdl_endpoint_url: ${PDL_ENDPOINT_URL}
  pdl_audience: ${PDL_AUDIENCE}
  unleash_url: ${UNLEASH_API_URL}
  unleash_instance_id: ${UNLEASH_INSTANCE_ID}
  meldinger_kommunenummer: ${MELDINGER_KOMMUNENUMMER}
  tokendings_url: ${TOKEN_X_WELL_KNOWN_URL}
  tokendings_client_id: ${TOKEN_X_CLIENT_ID}
  tokendings_private_jwk: ${TOKEN_X_PRIVATE_JWK}
  dialog_endpoint_url: ${DIALOG_ENDPOINT_URL}
  dialog_audience: ${DIALOG_AUDIENCE}
  vilkar_dokkrav_fagsystem_versjoner: ${VILKAR_DOKKRAV_FAGSYSTEM_VERSJONER}


#Maskinporten
maskinporten_clientid: ${MASKINPORTEN_CLIENT_ID}
maskinporten_scopes: ${MASKINPORTEN_SCOPES}
maskinporten_well_known_url: ${MASKINPORTEN_WELL_KNOWN_URL}
maskinporten_client_jwk: ${MASKINPORTEN_CLIENT_JWK}

#Token-validering
no.nav.security.jwt:
  issuer.selvbetjening:
    discoveryurl: ${LOGINSERVICE_IDPORTEN_DISCOVERY_URL}
    validation:
      optional-claims: aud,nbf
azuread.loginurl: ${AZUREAD_LOGINURL}

login_api_idporten_clientid: ${LOGIN_API_IDPORTEN_CLIENTID}

innsyn:
  vedlegg:
    virusscan:
      enabled: true
      url: ${CLAMAV_URL}
  cache:
    time_to_live_seconds: ${CACHE_TIME_TO_LIVE_SECONDS:10}
  retry:
    fiks:
      attempts: 5 # number of attempts
      initial_delay: 250 # initial delay in ms
      max_delay: 10000 # max delay in ms
