spring:
  profiles:
    active: mock
  redis:
    host: ${REDIS_HOST:localhost}
    port: 1212

server:
  servlet:
    context-path: '/sosialhjelp/innsyn-api'

management:
  endpoints:
    web:
      exposure:
        exclude: '*'

innsyn:
  vedlegg:
    virusscan:
      enabled: false
  cache:
    redis_mocked: true
    time_to_live_seconds: 2
  features:
    utbetalinger:
      enabled: true

client:
  fiks_digisos_endpoint_url: digisosapiurl
  fiks_dokumentlager_endpoint_url: dokumentlagerurl
  fiks_svar_ut_endpoint_url: svaruturl
  fiks_integrasjonid: integrasjonid
  fiks_integrasjonid_kommune: integrasjonidkommune
  fiks_integrasjonpassord: integrasjonpw
  fiks_integrasjonpassord_kommune: integrasjonpwkommune
  id_porten_token_url: tokenurl
  id_porten_client_id: clientid
  id_porten_scope: scope
  id_porten_config_url: configurl
  norg_endpoint_url: norgurl