spring:
  main:
    banner-mode: 'off'
  application:
    name: "sosialhjelp-innsyn-api"
  data:
    redis:
      host: localhost
      port: 6379
      password: pw
  session:
    store-type: redis
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 150MB

server:
  servlet:
    context-path: '/sosialhjelp/innsyn-api'
    session:
      cookie:
        name: sosialhjelp-innsyn-id
        path: /sosialhjelp
        secure: true
        max-age: 30M
        http-only: true
  max-http-request-header-size: 16KB
  shutdown: graceful

resilience4j:
  circuitbreaker:
    configs:
      default:
        # Settes høyt under innkjøring, default er at 50% av requests kan feile.
        failureRateThreshold: 75
    instances:
      pdl:
        # Endre dette til true når koden er kjørt inn
        registerHealthIndicator: false

# Prometheus
management:
  endpoints:
    web:
      base-path: "/internal"
      exposure:
        include: info, health, metrics, prometheus

springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED}
  swagger-ui:
    path: swagger-ui.html
  pathsToMatch: /**/api/v1/**

#Environment-variabler som settes av NAIS
client:
  fiks_digisos_endpoint_url: ${FIKS_DIGISOS_ENDPOINT_URL}
  fiks_dokumentlager_endpoint_url: ${FIKS_DOKUMENTLAGER_ENDPOINT_URL}
  fiks_svar_ut_endpoint_url: ${FIKS_SVAR_UT_ENDPOINT_URL}
  fiks_integrasjonid: ${INTEGRASJONSID_FIKS}
  fiks_integrasjonid_kommune: ${INTEGRASJONSID_FIKS_KOMMUNE}
  fiks_integrasjonpassord: ${INTEGRASJONPASSORD_FIKS}
  fiks_integrasjonpassord_kommune: ${INTEGRASJONPASSORD_FIKS_KOMMUNE}
  norg_url: ${NORG_URL}
  pdl_endpoint_url: ${PDL_ENDPOINT_URL}
  pdl_audience: ${PDL_AUDIENCE}
  unleash_instance_id: ${UNLEASH_INSTANCE_ID}
  unleash_env: ${UNLEASH_ENV}
  unleash_server_api_url: ${UNLEASH_SERVER_API_URL}
  unleash_server_api_token: ${UNLEASH_SERVER_API_TOKEN}
  vilkar_dokkrav_fagsystem_versjoner: ${VILKAR_DOKKRAV_FAGSYSTEM_VERSJONER}
  soknad_api_url: ${SOKNAD_API_URL}
  soknad_api_audience: ${SOKNAD_API_AUDIENCE}

#Token-validering
no.nav.security.jwt:
  issuer.selvbetjening:
    discoveryurl: ${LOGINSERVICE_IDPORTEN_DISCOVERY_URL}
    validation:
      optional-claims: aud,nbf

innsyn.loginurl: ${INNSYN_LOGINURL:null}

login_api_idporten_clientid: ${LOGIN_API_IDPORTEN_CLIENTID:dummy}

innsyn:
  vedlegg:
    virusscan:
      enabled: true
      url: ${CLAMAV_URL}
  cache:
    time_to_live_seconds: ${CACHE_TIME_TO_LIVE_SECONDS:10}
    dokument_cache_time_to_live_seconds: ${DOKUMENT_CACHE_TIME_TO_LIVE_SECONDS:3600}

retry_fiks_max_attempts: 5
retry_fiks_initial_delay: 100 # initial delay in ms

fiks-io:
  integrasjonspassord: ${FIKS_IO_INTEGRASJONSPASSORD:}
  integrasjonsid: ${FIKS_IO_INTEGRASJONSID:}
  private-key-path: "/var/run/secrets/key.der"
  kontoId: ${FIKS_IO_KONTO_ID:}
  virksomhetssertifikatPath: ${VIRKSERT_PATH:}
