innsyn:
  vedlegg:
    virusscan:
      enabled: false
      url:

springdoc:
  api-docs:
    enabled: true

#Token-validering
no.nav.security.jwt:
  issuer.selvbetjening:
    discoveryurl: http://localhost:${mock-oauth2-server.port}/selvbetjening/.well-known/openid-configuration
    accepted_audience: someaudience
    cookie_name: localhost-idtoken
azuread.loginurl: ${AZUREAD_LOGINURL:http://localhost:8080/sosialhjelp/innsyn-api/local/cookie}

client:
  fiks_digisos_endpoint_url: ${FIKS_DIGISOS_ENDPOINT_URL:https://api.fiks.test.ks.no}
  fiks_dokumentlager_endpoint_url: ${FIKS_DOKUMENTLAGER_ENDPOINT_URL:https://minside.fiks.test.ks.no}
  fiks_svar_ut_endpoint_url: ${FIKS_SVAR_UT_ENDPOINT_URL}
  fiks_integrasjonid: ${INTEGRASJONSID_FIKS}
  fiks_integrasjonid_kommune: ${INTEGRASJONSID_FIKS_KOMMUNE}
  fiks_integrasjonpassord: ${INTEGRASJONPASSORD_FIKS}
  fiks_integrasjonpassord_kommune: ${INTEGRASJONPASSORD_FIKS_KOMMUNE}
  norg_proxy_url: ${NORG_PROXY_URL:norg_endpoint_url}
  fss_proxy_audience: ${FSS_PROXY_AUDIENCE:fss-proxy-audience}
  fss_proxy_ping_url: ${FSS_PROXY_PING_URL:fss_proxy_ping_url}
  pdl_endpoint_url: ${PDL_ENDPOINT_URL:pdl_endpoint_url}
  pdl_audience: ${PDL_AUDIENCE:dummyAudience}
  unleash_url: ${UNLEASH_API_URL:https://unleash.nais.io/api}
  unleash_instance_id: ${UNLEASH_INSTANCE_ID:local}
  meldinger_kommunenummer: ${MELDINGER_KOMMUNENUMMER:0301}
  tokendings_url: ${TOKEN_X_WELL_KNOWN_URL:tokendings_endpoint_url}
  tokendings_client_id: ${TOKEN_X_CLIENT_ID:localhost:teamdigisos:sosialhjelp-dialog-api}
  tokendings_private_jwk: ${TOKEN_X_PRIVATE_JWK:generateRSA}
  dialog_endpoint_url: ${DIALOG_ENDPOINT_URL:dialog_endpoint_url}
  dialog_audience: ${DIALOG_AUDIENCE:dialog_audience}

#Maskinporten
maskinporten_clientid: maskinporten_clientid
maskinporten_scopes: scopes
maskinporten_well_known_url: ${MASKINPORTEN_WELL_KNOWN_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/well-known/maskinporten${mock-alt-api-wellknown-queryparam}}
maskinporten_client_jwk: generateRSA
