# Prometheus
management:
  endpoints:
    metrics.enabled: true
    web.exposure.include: prometheus
    export.prometheus.enabled: true
    prometheus.enabled: true

spring:
  main:
    banner-mode: 'off'

server:
  servlet:
    context-path: '/soknadsosialhjelp/innsyn-api'

client:
  fiks_digisos_endpoint_url: 'some url'
  fiks_svar_ut_endpoint_url: 'real svar-ut.com'
  fiks_dokumentlager_endpoint_url: 'real dokumentlager.com'