spring:
  profiles:
    active: mock
  redis:
    host: ${REDIS_HOST:localhost}
    port: 1212

server:
  servlet:
    context-path: '/sosialhjelp/innsyn-api'

innsyn:
  vedlegg:
    virusscan:
      enabled: false
  cache:
    redis_mocked: true
    time_to_live_seconds: 2