spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: 6379

innsyn:
  vedlegg:
    virusscan:
      enabled: false
  cache:
    redis_mocked: true

no.nav.security.jwt:
  issuer.selvbetjening:
    discoveryurl: http://metadata
    accepted_audience: aud-localhost
    cookie_name: localhost-idtoken