spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: 1212
    password: ${REDIS_PASSWORD:foobar}

server:
  servlet:
    context-path: '/sosialhjelp/innsyn-api'

management:
  endpoints:
    web:
      exposure:
        exclude: '*'

innsyn:
  vedlegg:
    virusscan:
      enabled: true
  cache:
    redis_mocked: true
    time_to_live_seconds: 2
  features:
    vilkar_enabled: true
    dokumentasjonkrav_enabled: true

client:
  fiks_digisos_endpoint_url: digisosapiurl
  fiks_dokumentlager_endpoint_url: dokumentlagerurl
  fiks_svar_ut_endpoint_url: svaruturl
  fiks_integrasjonid: integrasjonid
  fiks_integrasjonid_kommune: integrasjonidkommune
  fiks_integrasjonpassord: integrasjonpw
  fiks_integrasjonpassord_kommune: integrasjonpwkommune
  norg_endpoint_url: norgurl
  pdl_endpoint_url: pdlurl
  sts_token_endpoint_url: stsurl

idporten:
  token_url: tokenurl
  client_id: clientid
  scope: scope
  config_url: configurl
  truststore_type: truststoretype
  truststore_filepath: filepath
