spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: 6379

server:
  servlet:
    context-path: '/sosialhjelp/innsyn-api'

innsyn:
  vedlegg:
    virusscan:
      enabled: false
  cache:
    redis_mocked: true