innsyn:
  vedlegg:
    virusscan:
      enabled: false
      url:
  cache:
    dokument_cache_time_to_live_seconds: 100

springdoc:
  api-docs:
    enabled: true

#Token-validering
no.nav.security.jwt:
  issuer.selvbetjening:
    discoveryurl: http://localhost:${mock-oauth2-server.port}/selvbetjening/.well-known/openid-configuration
    accepted_audience: someaudience
    cookie_name: localhost-idtoken
innsyn.loginurl: ${INNSYN_LOGINURL:http://localhost:8080/sosialhjelp/innsyn-api/local/cookie}

login_api_idporten_clientid: clientId

client:
  fiks_digisos_endpoint_url: ${FIKS_DIGISOS_ENDPOINT_URL:https://api.fiks.test.ks.no}
  fiks_dokumentlager_endpoint_url: ${FIKS_DOKUMENTLAGER_ENDPOINT_URL:https://minside.fiks.test.ks.no}
  fiks_svar_ut_endpoint_url: ${FIKS_SVAR_UT_ENDPOINT_URL}
  fiks_integrasjonid: ${INTEGRASJONSID_FIKS}
  fiks_integrasjonid_kommune: ${INTEGRASJONSID_FIKS_KOMMUNE}
  fiks_integrasjonpassord: ${INTEGRASJONPASSORD_FIKS}
  fiks_integrasjonpassord_kommune: ${INTEGRASJONPASSORD_FIKS_KOMMUNE}
  norg_url: ${NORG_URL:norg_endpoint_url}
  pdl_endpoint_url: ${PDL_ENDPOINT_URL:pdl_endpoint_url}
  pdl_audience: ${PDL_AUDIENCE:dummyAudience}
  unleash_instance_id: "local"
  unleash_env: "local"
  unleash_server_api_url: "http://localhost:58888"
  unleash_server_api_token: "localtoken"
  tokendings_url: ${TOKEN_X_WELL_KNOWN_URL:tokendings_endpoint_url}
  tokendings_private_jwk: ${TOKEN_X_PRIVATE_JWK:generateRSA}
  vilkar_dokkrav_fagsystem_versjoner: ${VILKAR_DOKKRAV_FAGSYSTEM_VERSJONER}
  soknad_api_url: ${SOKNAD_API_URL:soknad_api_url}
  soknad_api_audience: ${SOKNAD_API_AUDIENCE:dummyAudience}


#Maskinporten
maskinporten_clientid: maskinporten_clientid
maskinporten_scopes: scopes
maskinporten_well_known_url: ${MASKINPORTEN_WELL_KNOWN_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/well-known/maskinporten${mock-alt-api-wellknown-queryparam}}
maskinporten_client_jwk: generateRSA
