# Prometheus
management:
  endpoints:
    metrics.enabled: true
    web.exposure.include: prometheus
    export.prometheus.enabled: true
    prometheus.enabled: true

spring:
  main:
    banner-mode: 'off'

server:
  servlet:
    context-path: '/soknadsosialhjelp/innsyn-api'

client:
  fiks_digisos_endpoint_url: ${FIKS_DIGISOS_ENDPOINT_URL:fiks-digisos-url}
  fiks_dokumentlager_endpoint_url: ${FIKS_DOKUMENTLAGER_ENDPOINT_URL:dokumentlager-url}
  fiks_integrasjonpassord: ${INTEGRASJONPASSORD_FIKS:fiks-integrasjonpassord}
  norg_endpoint_url: ${NORG_ENDPOINT_URL:norg_endpoint_url}

cors:
  allowed_origins:
    - "https://tjenester.nav.no/veivisersosialhjelp/"
    - "https://tjenester-q0.nav.no/veivisersosialhjelp/"
    - "https://tjenester-q1.nav.no/veivisersosialhjelp/"
    - "https://tjenester-t1.nav.no/veivisersosialhjelp/"