# Prometheus
management:
  endpoints:
    metrics.enabled: true
    web.exposure.include: prometheus
    export.prometheus.enabled: true
    prometheus.enabled: true

spring:
  main:
    banner-mode: 'off'

server:
  servlet:
    context-path: '/soknadsosialhjelp/innsyn-api'

cors:
  allowed_origins:
    - "https://tjenester.nav.no/veivisersosialhjelp/"
    - "https://tjenester-q0.nav.no/veivisersosialhjelp/"
    - "https://tjenester-q1.nav.no/veivisersosialhjelp/"
    - "https://tjenester-t1.nav.no/veivisersosialhjelp/"