server:
  servlet:
    context-path: '/sosialhjelp/innsyn-api'

spring:
  main:
    banner-mode: 'off'
  redis:
    host: ${REDIS_HOST:localhost}
    port: 6379

cors:
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:3001"

innsyn:
  vedlegg:
    virusscan:
      enabled: false