management:
  endpoints:
    web:
      exposure:
        exclude: '*'

innsyn:
  vedlegg:
    virusscan:
      enabled: false

client:
  fiks_digisos_endpoint_url: digisosapiurl
  fiks_dokumentlager_endpoint_url: dokumentlagerurl
  fiks_svar_ut_endpoint_url: svaruturl
  fiks_integrasjonid: integrasjonid
  fiks_integrasjonid_kommune: integrasjonidkommune
  fiks_integrasjonpassord: integrasjonpw
  fiks_integrasjonpassord_kommune: integrasjonpwkommune
  norg_endpoint_url: norgurl
  pdl_endpoint_url: pdlurl
  sts_token_endpoint_url: stsurl
  unleash_url: ${UNLEASH_API_URL:https://unleash.nais.io/api}
  unleash_instance_id: ${UNLEASH_INSTANCE_ID:local}

no.nav.sosialhjelp.idporten:
  token_url: tokenurl
  client_id: clientid
  scope: scope
  config_url: configurl
  truststore_type: truststoretype
  truststore_filepath: filepath


#Token-validering
no.nav.security.jwt:
  issuer.selvbetjening:
    discoveryurl: http://metadata
    accepted_audience: aud-localhost
    cookie_name: localhost-idtoken
azuread.loginurl: ${AZUREAD_LOGINURL:http://localhost:8080/sosialhjelp/innsyn-api/local/cookie}