cors:
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:3001"
    - "https://www.digisos-test.com"
    - "https://tjenester.nav.no/veivisersosialhjelp/"
    - "https://tjenester-q0.nav.no/veivisersosialhjelp/"
    - "https://tjenester-q1.nav.no/veivisersosialhjelp/"
    - "https://tjenester-t1.nav.no/veivisersosialhjelp/"