spring:
  application:
    name: "sosialhjelp-innsyn-api-dev"
  data:
    redis:
      password: ${REDIS_PASSWORD_CACHE:pw}
      host: ${REDIS_HOST_CACHE}
      username: ${REDIS_USERNAME_CACHE}
      port: ${REDIS_PORT_CACHE}
      ssl:
        enabled: true
