management:
  endpoints:
    web:
      base-path: "/internal"
      exposure:
        exclude: '*'

innsyn:
  vedlegg:
    virusscan:
      enabled: false
      url:

springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED:true}

mock-alt-api-host: ${MOCK_ALT_API_HOST:127.0.0.1}
mock-alt-api-wellknown-queryparam: ${MOCK_ALT_API_WELLKNOWN_QUERYPARAM:}

#Token-validering
no.nav.security.jwt:
  issuer.selvbetjening:
    discoveryurl: ${METADATA_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/well-known/selvbetjening${mock-alt-api-wellknown-queryparam}}
#    accepted_audience: someaudience
#    cookie_name: localhost-idtoken
    validation:
      optional-claims: aud,nbf
innsyn.loginurl: ${INNSYN_LOGINURL:http://localhost:8080/sosialhjelp/innsyn-api/oauth2/login}

login_api_idporten_clientid: clientId

client:
  fiks_digisos_endpoint_url: ${FIKS_DIGISOS_ENDPOINT_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/fiks}
  fiks_dokumentlager_endpoint_url: ${FIKS_DOKUMENTLAGER_ENDPOINT_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/fiks/dokumentlager}
  fiks_svar_ut_endpoint_url: ${FIKS_SVAR_UT_ENDPOINT_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/fiks/svarut}
  fiks_integrasjonid: ${INTEGRASJONSID_FIKS:id1}
  fiks_integrasjonid_kommune: ${INTEGRASJONSID_FIKS_KOMMUNE:id2}
  fiks_integrasjonpassord: ${INTEGRASJONPASSORD_FIKS:pw1}
  fiks_integrasjonpassord_kommune: ${INTEGRASJONPASSORD_FIKS_KOMMUNE:pw2}
  norg_url: ${NORG_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/norg_endpoint_url/}
  pdl_endpoint_url: ${PDL_ENDPOINT_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/pdl_endpoint_url}
  pdl_audience: ${PDL_AUDIENCE:dummyAudience}
  unleash_url: ${UNLEASH_API_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/internal/unleash}
  unleash_instance_id: ${UNLEASH_INSTANCE_ID:local}
  meldinger_kommunenummer: ${MELDINGER_KOMMUNENUMMER:0301}
  tokendings_url: ${TOKEN_X_WELL_KNOWN_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/well-known/selvbetjening${mock-alt-api-wellknown-queryparam}}
  tokendings_client_id: ${TOKEN_X_CLIENT_ID:localhost:teamdigisos:sosialhjelp-dialog-api}
  tokendings_private_jwk: ${TOKEN_X_PRIVATE_JWK:generateRSA}
  dialog_endpoint_url: ${DIALOG_ENDPOINT_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/dialog-api/status}
  dialog_audience: ${DIALOG_AUDIENCE:dialog_audience}
  vilkar_dokkrav_fagsystem_versjoner: ${VILKAR_DOKKRAV_FAGSYSTEM_VERSJONER}


#Maskinporten
maskinporten_clientid: maskinporten_clientid
maskinporten_scopes: scopes
maskinporten_well_known_url: ${MASKINPORTEN_WELL_KNOWN_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/well-known/maskinporten${mock-alt-api-wellknown-queryparam}}
maskinporten_client_jwk: generateRSA

idporten_well_known_url: ${IDPORTEN_WELL_KNOWN_URL:https://oidc-ver2.difi.no/idporten-oidc-provider/.well-known/openid-configuration}
idporten_clientid: ${IDPORTEN_CLIENT_ID:clientId}
idporten_client_jwk: ${IDPORTEN_CLIENT_JWK:generateRSA}
idporten_redirect_uri: ${IDPORTEN_REDIRECT_URI:https://www-q0.dev.nav.no/sosialhjelp/innsyn-api/oauth2/callback}
