version: 2
defaults: &defaults
  docker:
    - image: "circleci/openjdk:11-jdk"
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Create workspace
          command: mkdir -p /tmp/workspace
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
      - run:
          name: build
          command: ./gradlew test build
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - run:
          name: Copy jars to workspace
          command: cp build/libs/*-all.jar /tmp/workspace
      - persist_to_workspace:
          root: /tmp/workspace
          paths: "*.jar"
  release:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Copy jar to expected path
          command: |
            cp /tmp/workspace/*.jar .
      - run:
          name: Build and push to docker hub
          command: |
            VERSION="$(./gradlew -q printVersion)"
            GIT_HASH="$(git rev-parse HEAD)"
            echo "Extracted version = \"$VERSION\""
            echo "Extracted git hash = \"$GIT_HASH\""
            docker build -t navikt/sosialhjelp-innsyn-api:latest -f Dockerfile .
            docker tag navikt/sosialhjelp-innsyn-api:latest "navikt/sosialhjelp-innsyn-api:$VERSION"
            docker tag navikt/sosialhjelp-innsyn-api:latest "navikt/sosialhjelp-innsyn-api:$GIT_HASH"
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push "navikt/sosialhjelp-innsyn-api:latest"
            docker push "navikt/sosialhjelp-innsyn-api:$VERSION"
            docker push "navikt/sosialhjelp-innsyn-api:$GIT_HASH"
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master