version: 2

jobs:
  build:
    docker:
      - image: "circleci/openjdk:11-jdk"
    steps:
      - checkout
      - run:
          name: Create workspace
          command: mkdir -p /tmp/workspace
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
      - run:
          name: test and build
          command: ./gradlew test build
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - run:
          name: Copy jars to workspace
          command: cp build/libs/*.jar /tmp/workspace
      - persist_to_workspace:
          root: /tmp/workspace
          paths: "*.jar"
  release:
    docker:
      - image: "circleci/openjdk:11-jdk"
    context: NAIS deployment
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Copy jar to expected path
          command: |
            cp /tmp/workspace/*.jar .
      - run:
          name: Generate version number and docker image tags
          command: |
            export GIT_COMMIT_HASH=$(git log -n 1 --pretty=format:'%h')
            export GIT_COMMIT_DATE=$(git log -1 --pretty='%ad' --date=format:'%Y%m%d.%H%M')
            export VERSION=1.0_${GIT_COMMIT_DATE}_${GIT_COMMIT_HASH}
            echo $VERSION > ./VERSION.txt

            echo "export DOCKER_TAG=\"docker.pkg.github.com/navikt/$CIRCLE_PROJECT_REPONAME/$CIRCLE_PROJECT_REPONAME:$VERSION\"" >> $BASH_ENV
      - run:
          name: Build docker image
          command: docker build -t $DOCKER_TAG .
      - run:
          # Push the image to Docker Packages, can also be used against dockerhub by omitting docker.pkg.github.com
          name: Docker push
          context: NAIS deployment
          command: |
            set -eo pipefail
            git clone https://github.com/navikt/github-apps-support.git
            export PATH=`pwd`/github-apps-support/bin:$PATH
            echo $DIGISOS_KEY | tr '_' '\n' > digisos.key
            export GH_TOKEN=$(generate-installation-token.sh `generate-jwt.sh digisos.key $DIGISOS_APPID`)
            echo -e "machine api.github.com login x-access-token password $GH_TOKEN" > ~/.netrc
            rm digisos.key

            echo "docker login $DOCKER_LOGIN"

            echo $GH_TOKEN > ./GH_TOKEN.txt

            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin docker.pkg.github.com
            echo $DOCKER_TAG
            docker push $DOCKER_TAG
      - persist_to_workspace:
          root: .
          paths:
            - ./VERSION.txt
            - ./GH_TOKEN.txt

  deploy_dev:
    docker:
      - image: navikt/deployment-cli:v0.2.0
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/workspace
      - run: # Brukernavn og passord til Github ligger i miljøvariablene DEPLOYMENT_USERNAME og DEPLOYMENT_PASSWORD.
          name: Deploy til default dev-sbs
          command: |
            export VERSION=$(cat /tmp/workspace/VERSION.txt)
            export GH_TOKEN=$(cat /tmp/workspace/GH_TOKEN.txt)

            echo "temporary token $GH_TOKEN"

            deployment-cli deploy create --cluster=dev-sbs --repository=navikt/sosialhjelp-innsyn-api --team=digisos -r=nais.yaml --var version=${VERSION} --vars=nais/dev/default.json

  deploy_miljo:
    docker:
      - image: navikt/deployment-cli:v0.2.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Deploy versjon=${VERSION} til miljø=${MILJO} i dev-sbs
          command: |
            deployment-cli deploy create --cluster=dev-sbs --repository=navikt/sosialhjelp-innsyn-api --team=digisos -r=nais.yaml --var version=${VERSION} --vars=nais/dev/${MILJO}.json

  deploy_prod:
    docker:
      - image: navikt/deployment-cli:v0.2.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Deploy versjon=${VERSION} til prod
          command: |
            deployment-cli deploy create --cluster=prod-sbs --repository=navikt/sosialhjelp-innsyn-api --team=digisos -r=nais.yaml --var version=${VERSION} --vars=nais/prod/default.json

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build

      - release:
          requires:
            - build

      - deploy_dev:
          requires:
            - release
          filters:
            branches:
              only: master