version: 2
defaults: &defaults
  docker:
    - image: "circleci/openjdk:11-jdk"
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Create workspace
          command: mkdir -p /tmp/workspace
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
      - run:
          name: build
          command: ./gradlew test build
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - run:
          name: Copy jars to workspace
          command: cp build/libs/*.jar /tmp/workspace
      - persist_to_workspace:
          root: /tmp/workspace
          paths: "*.jar"
  release:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Copy jar to expected path
          command: |
            cp /tmp/workspace/*.jar .
      - run:
          name: Build and push to docker hub
          command: |
            VERSION="$(./gradlew -q printVersion)"
            GIT_HASH="$(git rev-parse HEAD)"
            echo "Extracted version = \"$VERSION\""
            echo "Extracted git hash = \"$GIT_HASH\""
            docker build -t navikt/sosialhjelp-innsyn-api:latest -f Dockerfile .
            docker tag navikt/sosialhjelp-innsyn-api:latest "navikt/sosialhjelp-innsyn-api:$VERSION"
            docker tag navikt/sosialhjelp-innsyn-api:latest "navikt/sosialhjelp-innsyn-api:$GIT_HASH"
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin
            docker push "navikt/sosialhjelp-innsyn-api:latest"
            docker push "navikt/sosialhjelp-innsyn-api:$VERSION"
            docker push "navikt/sosialhjelp-innsyn-api:$GIT_HASH"

  deploy_dev:
    docker:
      - image: navikt/deployment-cli:v0.1.5
    steps:
      - checkout
      - setup_remote_docker
      - run: # Brukernavn og passord til Github ligger i miljøvariablene DEPLOYMENT_USERNAME og DEPLOYMENT_PASSWORD.
          name: Deploy til default dev-sbs
          command: |
            deployment-cli deploy create --cluster=dev-sbs --repository=navikt/sosialhjelp-innsyn-api --team=digisos -r=nais.yaml --version=${CIRCLE_SHA1} --vars=nais/dev/default.json

  deploy_miljo:
    docker:
      - image: navikt/deployment-cli:v0.1.5
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Deploy til ${MILJO} dev-sbs
          command: |
            deployment-cli deploy create --cluster=dev-sbs --repository=navikt/sosialhjelp-innsyn-api --team=digisos -r=nais.yaml --version=${VERSION} --vars=nais/dev/${MILJO}.json

  deploy_prod:
    docker:
      - image: navikt/deployment-cli:v0.1.5
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Deploy til prod
          command: |
            deployment-cli deploy create --cluster=prod-sbs --repository=navikt/sosialhjelp-innsyn-api --team=digisos -r=nais.yaml --version=${VERSION} --vars=nais/prod/default.json

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build

      - release:
          context: NAIS deployment
          requires:
            - build
          filters:
            branches:
              only: master

      - deploy_dev:
          requires:
            - release
          filters:
            branches:
              only: master