schema: pdl-api-schema.graphqls
extensions:
  endpoints:
    PDL GraphQL Endpoint:
      url: https://pdl-playground.dev.intern.nav.no/graphql
      headers:
        user-agent: ''
      introspect: false
