package no.nav.sosialhjelp.innsyn.idporten

object CachePrefixes {
    const val REFRESH_TOKEN_CACHE_PREFIX = "IDPORTEN_REFRESH_TOKEN_"
    const val ACCESS_TOKEN_CACHE_PREFIX = "IDPORTEN_ACCESS_TOKEN_"
    const val ID_TOKEN_CACHE_PREFIX = "IDPORTEN_ID_TOKEN_"
    const val SESSION_ID_CACHE_PREFIX = "IDPORTEN_SESSION_ID_"

    const val STATE_CACHE_PREFIX = "IDPORTEN_STATE_"
    const val NONCE_CACHE_PREFIX = "IDPORTEN_NONCE_"
    const val CODE_VERIFIER_CACHE_PREFIX = "IDPORTEN_CODE_VERIFIER_"

    const val LOGIN_REDIRECT_CACHE_PREFIX = "LOGIN_REDIRECT_"
}
