apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-innsyn-api
  namespace: default
  labels:
    team: digisos
spec:
  image: "navikt/sosialhjelp-innsyn-api:{{version}}"
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /internal/isReady
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /actuator/metrics
  replicas:
    min: 1
    max: 4
  webproxy: true
  vault:
    enabled: false
  ingresses:
    - "https://sosialhjelp-innsyn-api.nais.oera-q.local/sosialhjelp/innsyn-api"
    - "https://www-q0.nav.no/sosialhjelp/innsyn-api"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi