apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-innsyn-api
  namespace: "{{namespace}}"
  labels:
    team: digisos
spec:
  image: "navikt/sosialhjelp-innsyn-api:{{version}}"
  port: 8080
  liveness:
    path: /sosialhjelp/innsyn-api/internal/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /sosialhjelp/innsyn-api/internal/isReady
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /actuator/metrics
  replicas:
    min: 1
    max: 4
  webproxy: true
  vault:
    enabled: false
  ingresses: {{{ingresses}}}
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi