apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{applicationName}}
  namespace: {{namespace}}
  labels:
    team: teamdigisos
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /sosialhjelp/innsyn-api/internal/isAlive
    initialDelay: 45
    timeout: 1
    periodSeconds: 10
    failureThreshold: 10
  readiness:
    path: /sosialhjelp/innsyn-api/internal/isReady
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: {{prometheusEnabled}}
    path: /sosialhjelp/innsyn-api/internal/prometheus
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
  webproxy: {{webProxyEnabled}}
{{#if isGcp}}
  accessPolicy:
    outbound:
      external:
        - host: "oidc-ver2.difi.no"
        - host: "unleash.nais.io"
      rules:
        - application: sosialhjelp-mock-alt-api
        - application: sosialhjelp-innsyn-api-redis
{{/if}}
{{#if isGcp}}
  filesFrom:
    - secret: virksomhetssertifikat
{{/if}}
{{#if isGcp}}
  tracing:
    enabled: true
{{/if}}
  vault:
    enabled: {{vaultEnabled}}
{{#if vaultEnabled}}
    paths:
{{#each kvPaths}}
      - mountPath: {{@key}}
        kvPath: {{this}}
{{/each}}
{{/if}}
  ingresses:
{{#each ingress}}
    - "{{this}}"
{{/each}}
  resources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 1Gi
  env:
{{#each env}}
    - name: {{@key}}
      value: "{{this}}"
{{/each}}
  envFrom:
    - configmap: loginservice-idporten
    - secret: redis-password-innsyn-api