apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: teamdigisos
  annotations:
    "nais.io/run-as-group": "0"
    "nais.io/read-only-file-system": "false"
  name: sosialhjelp-innsyn-api-redis
  namespace: teamdigisos
spec:
  image: bitnami/redis:6.0.16
  port: 6379
  replicas: # A single Redis-app doesn't scale
    min: 1
    max: 1 # More replicas doesn't sync
  resources: # you need to monitor the resource usage yourself
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 2m
      memory: 128Mi
  accessPolicy: # for GCP
    inbound:
      rules:
        - application: sosialhjelp-innsyn-api
        - application: sosialhjelp-innsyn-api-redisexporter
        - application: sosialhjelp-innsyn-api-q
  service:
    port: 6379
    protocol: redis
  envFrom:
    - secret: redis-password-innsyn-api