apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-innsyn-api
  namespace: teamdigisos
  labels:
    team: teamdigisos
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "150M"
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /sosialhjelp/innsyn-api/internal/isAlive
    initialDelay: 45
    timeout: 1
    periodSeconds: 10
    failureThreshold: 10
  readiness:
    path: /sosialhjelp/innsyn-api/internal/isReady
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /sosialhjelp/innsyn-api/internal/prometheus
  replicas:
    min: 1
    max: 2
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  webproxy: true
  tokenx:
    enabled: true
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "ks:fiks"
  ingresses:
    - "https://sosialhjelp-innsyn-api.dev-fss-pub.nais.io/sosialhjelp/innsyn-api"
    - "https://sosialhjelp-innsyn-api.dev.intern.nav.no/sosialhjelp/innsyn-api"
  resources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 10m
      memory: 512Mi
  envFrom:
    - configmap: loginservice-idporten
    - secret: redis-password-innsyn-api
    - secret: testbruker-natalie
    - secret: fiks-integrasjon-secret
    - secret: fiks-kommune-integrasjon-secret
    - secret: sosialhjelp-innsyn-api-unleash-api-token
    - secret: fiks-io-integrasjonspassord
  filesFrom:
    - secret: fiks-io-private-key
  vault:
    enabled: true
    paths:
      - kvPath: "/secret/virksomhetssertifikat/preprod/shared"
        mountPath: "/var/run/secrets/nais.io/virksomhetssertifikat"
  accessPolicy:
    outbound:
      external:
        - host: teamdigisos-unleash-api.nav.cloud.nais.io
  env:
    - name: FIKS_DIGISOS_ENDPOINT_URL
      value: "https://api.fiks.test.ks.no"
    - name: FIKS_DOKUMENTLAGER_ENDPOINT_URL
      value: "https://minside.fiks.test.ks.no"
    - name: FIKS_SVAR_UT_ENDPOINT_URL
      value: "https://test.svarut.ks.no"
    - name: NORG_URL
      value: "https://norg2.dev.intern.nav.no/norg2/api/v1"
    - name: INNSYN_LOGINURL
      value: "https://login.ekstern.dev.nav.no/oauth2/login"
    - name: CACHE_TIME_TO_LIVE_SECONDS
      value: "10"
    - name: DOKUMENT_CACHE_TIME_TO_LIVE_SECONDS
      value: "3600"
    - name: REDIS_HOST
      value: "sosialhjelp-innsyn-api-redis.teamdigisos.svc.nais.local"
    - name: SPRING_PROFILES_ACTIVE
      value: "dev-fss,log-kibana"
    - name: PDL_ENDPOINT_URL
      value: "https://pdl-api.dev.intern.nav.no/graphql"
    - name: PDL_AUDIENCE
      value: "dev-fss:pdl:pdl-api"
    - name: UNLEASH_INSTANCE_ID
      value: "sosialhjelp-innsyn-api"
    - name: UNLEASH_ENV
      value: "dev-fss"
    - name: SWAGGER_ENABLED
      value: "true"
    - name: CLAMAV_URL
      value: "http://clamav.nais-system.svc.nais.local/scan"
    - name: LOGIN_API_IDPORTEN_CLIENTID
      value: "9664fbe4-a807-4914-95f4-12146085d23c"
    - name: VILKAR_DOKKRAV_FAGSYSTEM_VERSJONER
      value: "Socio;10.1.16,mock-alt;1.0-MOCKVERSJON"
    - name: SOKNAD_API_URL
      value: "http://sosialhjelp-soknad-api/sosialhjelp/soknad-api"
    - name: SOKNAD_API_AUDIENCE
      value: "dev-fss:teamdigisos:sosialhjelp-soknad-api"
    - name: MASKINPORTEN_WELL_KNOWN_URL
      value: "https://test.maskinporten.no/.well-known/oauth-authorization-server"
    - name: FIKS_IO_INTEGRASJONSID
      value: "6839eedd-8007-432b-a24d-67bd845f6369"
    - name: FIKS_IO_KONTO_ID
      value: 46bbe668-3468-45fa-9bd1-67b5469b7361
    - name: VIRKSERT_PATH
      value: "/var/run/secrets/nais.io/virksomhetssertifikat"
