apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-innsyn-api-mock
  namespace: teamdigisos
  labels:
    team: teamdigisos
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "150M"
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /sosialhjelp/innsyn-api/internal/isAlive
    initialDelay: 45
    timeout: 1
    periodSeconds: 10
    failureThreshold: 10
  readiness:
    path: /sosialhjelp/innsyn-api/internal/isReady
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: false
  replicas:
    min: 1
    max: 1
  accessPolicy:
    outbound:
      external:
        - host: "unleash.nais.io"
      rules:
        - application: sosialhjelp-mock-alt-api-mock
        - application: sosialhjelp-soknad-api-mock
  ingresses:
    - "https://sosialhjelp-innsyn-api-mock.dev.nav.no/sosialhjelp/innsyn-api"
  resources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 10m
      memory: 512Mi
  envFrom:
    - configmap: loginservice-idporten
    - secret: redis-password-innsyn-api
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: "mock-alt,log-console,mock-redis"
    - name: METADATA_URL
      value: "https://digisos.ekstern.dev.nav.no/sosialhjelp/mock-alt-api/well-known/selvbetjening"
    - name: FIKS_DIGISOS_ENDPOINT_URL
      value: "http://sosialhjelp-mock-alt-api-mock/sosialhjelp/mock-alt-api/fiks"
    - name: FIKS_DOKUMENTLAGER_ENDPOINT_URL
      value: "https://digisos.ekstern.dev.nav.no/sosialhjelp/mock-alt-api/fiks/dokumentlager"
    - name: FIKS_SVAR_UT_ENDPOINT_URL
      value: "http://sosialhjelp-mock-alt-api-mock/sosialhjelp/mock-alt-api/fiks/svarut"
    - name: AZUREAD_LOGINURL
      value: "https://digisos.ekstern.dev.nav.no/sosialhjelp/mock-alt/login"
    - name: NORG_URL
      value: "http://sosialhjelp-mock-alt-api-mock/sosialhjelp/mock-alt-api/norg_endpoint_url"
    - name: PDL_ENDPOINT_URL
      value: "http://sosialhjelp-mock-alt-api-mock/sosialhjelp/mock-alt-api/pdl_endpoint_url"
    - name: UNLEASH_API_URL
      value: "https://unleash.nais.io/api"
    - name: UNLEASH_INSTANCE_ID
      value: "mock"
    - name: REDIS_HOST
      value: "sosialhjelp-innsyn-api-redis.teamdigisos.svc.cluster.local"
    - name: TOKEN_X_WELL_KNOWN_URL
      value: "http://sosialhjelp-mock-alt-api-mock/sosialhjelp/mock-alt-api/well-known/tokenx"
    - name: TOKEN_X_CLIENT_ID
      value: "dev-gcp:teamdigisos:sosialhjelp-innsyn-api-mock"
    - name: MASKINPORTEN_WELL_KNOWN_URL
      value: "http://sosialhjelp-mock-alt-api-mock/sosialhjelp/mock-alt-api/well-known/maskinporten"
    - name: VILKAR_DOKKRAV_FAGSYSTEM_VERSJONER
      value: "Socio;10.1.16,mock-alt;1.0-MOCKVERSJON,Testsystemet;1.0.0"
    - name: SOKNAD_API_URL
      value: "http://sosialhjelp-soknad-api-mock/sosialhjelp/soknad-api"
