apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-innsyn-api
  namespace: teamdigisos
  labels:
    team: teamdigisos
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "150M"
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /sosialhjelp/innsyn-api/internal/isAlive
    initialDelay: 45
    timeout: 1
    periodSeconds: 10
    failureThreshold: 10
  readiness:
    path: /sosialhjelp/innsyn-api/internal/isReady
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /sosialhjelp/innsyn-api/internal/prometheus
  replicas:
    min: 1
    max: 1
  tokenx:
    enabled: true
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "ks:fiks"
  accessPolicy:
    outbound:
      external:
        - host: api.fiks.test.ks.no
        - host: minside.fiks.test.ks.no
        - host: pdl-api.dev-fss-pub.nais.io
        - host: norg2.dev-fss-pub.nais.io
        - host: unleash.nais.io
        - host: teamdigisos-unleash-api.nav.cloud.nais.io
        - host: test.idporten.no
      rules:
        - application: clamav
          namespace: clamav
    inbound:
      rules:
        - application: sosialhjelp-innsyn
  resources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 10m
      memory: 512Mi
  redis:
    - instance: cache
      access: readwrite
  envFrom:
    - secret: fiks-integrasjon-secret
    - secret: fiks-kommune-integrasjon-secret
    - secret: sosialhjelp-innsyn-api-unleash-api-token
  env:
    - name: IDPORTEN_WELL_KNOWN_URL
      value: "https://test.idporten.no/.well-known/openid-configuration"
    - name: SPRING_PROFILES_ACTIVE
      value: "log-kibana,preprod"
    - name: FIKS_DIGISOS_ENDPOINT_URL
      value: "https://api.fiks.test.ks.no"
    - name: FIKS_DOKUMENTLAGER_ENDPOINT_URL
      value: "https://minside.fiks.test.ks.no"
    - name: NORG_URL
      value: "https://norg2.dev-fss-pub.nais.io/norg2/api/v1"
    - name: CACHE_TIME_TO_LIVE_SECONDS
      value: "10"
    - name: DOKUMENT_CACHE_TIME_TO_LIVE_SECONDS
      value: "3600"
    - name: PDL_ENDPOINT_URL
      value: "https://pdl-api.dev-fss-pub.nais.io/graphql"
    - name: PDL_AUDIENCE
      value: "dev-fss:pdl:pdl-api"
    - name: UNLEASH_INSTANCE_ID
      value: "sosialhjelp-innsyn-api"
    - name: UNLEASH_ENV
      value: "dev"
    - name: SWAGGER_ENABLED
      value: "true"
    - name: CLAMAV_URL
      value: "http://clamav.nais-system.svc.nais.local/scan"
    - name: VILKAR_DOKKRAV_FAGSYSTEM_VERSJONER
      value: "Socio;10.1.16,mock-alt;1.0-MOCKVERSJON"
    - name: MASKINPORTEN_WELL_KNOWN_URL
      value: "https://test.maskinporten.no/.well-known/oauth-authorization-server"
    - name: IDPORTEN_POST_LOGOUT_REDIRECT_URI
      value: "https://www.dev.nav.no/no/utlogget"
