name: 'Deploy to Production'
on:
  workflow_run:
    workflows: ["Build Kotlin, Run Lint and Test"]
    branches: [master]
    types:
      - completed
  repository_dispatch:
    types: [deploy_prod_tag]

jobs:
  deploy-fss:
    name: 'Deploy to prod-fss'
    if: ${{ github.event_name == 'repository_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    permissions:
      id-token: write
      contents: write
    uses: navikt/sosialhjelp-ci/.github/workflows/deploy_app.yml@v3
    with:
      cluster-name: 'prod-fss'
      resource-folder: 'prod'
      resource-name: 'prod-fss'
    secrets: inherit

