name: Trigger Repo B

on:
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Trigger repository dispatch
        run: |
          curl --fail-with-body -X POST \
            -H "Authorization: Bearer ${{ steps.app-token.outputs.token }}" \
            -H "Accept: application/vnd.github+json" \
            -H "Content-Type: application/json" \
            https://api.github.com/repos/navikt/digisos-docker-compose/dispatches \
            -d '{"event_type":"trigger-from-repo-a"}'